### ISSUE TITLE
Issues to be fixed

### ISSUE THREAD

**Issue by pkbhowmick** [Superm4n97/Book-Server#1]
error handling: https://github.com/Superm4n97/Book-Server/blob/main/handlers/handlers.go#L29, https://github.com/Superm4n97/Book-Server/blob/main/handlers/handlers.go#L42, https://github.com/Superm4n97/Book-Server/blob/main/handlers/handlers.go#L137, https://github.com/Superm4n97/Book-Server/blob/main/middlewares/tokenGeneration.go#L18

check given book id is already exist or not: https://github.com/Superm4n97/Book-Server/blob/main/handlers/handlers.go#L61

check key exist in the map properly: https://github.com/Superm4n97/Book-Server/blob/main/handlers/handlers.go#L76
example: val, found := mp[key]

Use env variables for secrets: https://github.com/Superm4n97/Book-Server/blob/main/model/model.go#L16-L19

Return errors from functions and make decision based on the error: https://github.com/Superm4n97/Book-Server/blob/main/middlewares/authentication.go#L90-L92

**Comment by Superm4n97** [comment]
issues fixed
